// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/vue-3-vite/drag-onto-tasks/src/App.vue
<script setup lang="ts">

import { onMounted, onUnmounted, reactive, ref } from 'vue';
import { BryntumCalendar, BryntumDemoHeader, BryntumGrid, BryntumSplitter } from '@bryntum/calendar-vue-3';
import { equipmentGridConfig, eventEditFeatureConfig, filterBarFeatureConfig, myCalendarConfig } from './AppConfig';
import type { CrudManagerConfig, Model } from '@bryntum/calendar';
import Drag from './lib/Drag';
import { equipmentStore } from './lib/EquipmentStore';

const
    calendarConfig = reactive(myCalendarConfig),
    gridConfig     = reactive(equipmentGridConfig),
    calendarRef    = ref(null),
    gridRef        = ref(null),
    dragRef        = ref(null);

// Configure crudManager in App.vue to access equipmentStore and prevent the equipment object to be a proxy object (as returned value from vue reactive)
const crudManagerConfig: CrudManagerConfig = {
    // CrudManager arranges loading and syncing of data in JSON form from/to a web service
    crudStores : [equipmentStore],
    loadUrl    : 'data/data.json',
    autoLoad   : true,
    eventStore : {
        fields : [
            // A custom equipment field where we store items assigned to the task
            {
                name : 'equipment',
                convert(data) {
                    return (data || []).map((id: string | number | Model) => equipmentStore.getById(id));
                }
            }
        ]
    }
};

onMounted(() => {
    const
        calendar = calendarRef.value.instance.value,
        grid     = gridRef.value.instance!.value;

    // event renderer expects equipmentStore to be class property of calendar
    // equipmentStore is not a default property of calendar so it is assigned here instead of in calendar configuration
    calendar['equipmentStore'] = equipmentStore;

    // Assign grid store to equipmentStore
    const gridStore = grid.store = equipmentStore;

    const equipmentCombo = calendar!.eventEdit.editor.widgetMap.equipment;
    // Use a chained Store to avoid its filtering to interfere with calendar's rendering
    equipmentCombo.store = gridStore.chain();

    dragRef.value = new Drag({
        grid,
        calendar,
        outerElement : grid.element
    });
});

// To destroy Drag instance to avoid potential side effects or memory leaks after component is unmounted
onUnmounted(() => {
    (dragRef as Drag)?.current?.destroy?.();
});

</script>

<template>
    <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
    <bryntum-demo-header />
    <div id="calendar-container">
        <bryntum-calendar
            ref="calendarRef"
            v-bind="calendarConfig"
            :crud-manager="crudManagerConfig"
            :event-edit-feature="eventEditFeatureConfig"
        />
        <bryntum-splitter />
        <bryntum-grid
            ref="gridRef"
            v-bind="gridConfig"
            :filter-bar-feature="filterBarFeatureConfig"
            :cell-edit-feature="false"
        />
    </div>
</template>

<style lang="scss">
@import './App.scss';
</style>

// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/react-vite/drag-onto-tasks/src/App.tsx
import { BryntumCalendar, BryntumDemoHeader, BryntumGrid, BryntumSplitter } from '@bryntum/calendar-react';
import { type Combo, Store } from '@bryntum/calendar';
import { equipmentGridConfig, useCalendarConfig } from './AppConfig';
import { useEffect, useRef } from 'react';
import Drag from './lib/Drag';
import './App.scss';

function App() {
    const
        calendarRef = useRef<BryntumCalendar>(null),
        gridRef     = useRef<BryntumGrid>(null),
        dragRef     = useRef<Drag>(null),

        // Costume equipmentStore configuration
        equipmentStore = new Store({
            id     : 'equipment',
            fields : [
                'name',
                'iconCls'
            ],
            sorters : [
                { field : 'name', ascending : true }
            ]
        });

    const calendarConfig = useCalendarConfig(equipmentStore);

    useEffect(() => {
        const
            grid     = gridRef.current!.instance,
            calendar = calendarRef.current!.instance;

        if (calendar && grid) {

            const
                // Assign grid store to equipmentStore
                gridStore      = grid.store = equipmentStore,
                equipmentCombo = calendar.features.eventEdit.editor.widgetMap['equipment'] as Combo;

            // Use a chained Store to avoid it's filtering to interfere with calendar's rendering
            equipmentCombo.store = gridStore.chain();

            (dragRef as Drag).current = new Drag({
                grid,
                calendar,
                outerElement : grid.element
            });

            // We need to destroy Drag instance because React 18 Strict mode
            // runs this component twice in development mode, and Drag has no
            // UI, so it is not destroyed automatically as grid and scheduler.
            return () => (dragRef as Drag).current?.destroy?.();
        }
    }, [gridRef, calendarRef, dragRef, equipmentStore]);

    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader/>
            <div id="calendar-container">
                <BryntumCalendar
                    ref={calendarRef}
                    {...calendarConfig}
                />
                <BryntumSplitter/>
                <BryntumGrid
                    ref={gridRef}
                    {...equipmentGridConfig}
                />
            </div>
        </>
    );
}

export default App;
