// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/vue-3-vite/listview/src/App.vue
<script setup lang="ts">

import { reactive } from 'vue';
import { BryntumCalendar, BryntumDemoHeader } from '@bryntum/calendar-vue-3';
import { calendarConfiguration } from './AppConfig';

const calendarConfig = reactive(calendarConfiguration);

</script>

<template>
    <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
    <bryntum-demo-header />
    <bryntum-calendar
        v-bind="calendarConfig"
    />
</template>

<style lang="scss">
@import './App.scss';
</style>

// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/react-vite/basic-thin/src/App.tsx
import React, { Fragment, FunctionComponent, useRef, useEffect } from 'react';
import { BryntumDemoHeader } from '@bryntum/core-react-thin';
import { BryntumCalendar } from '@bryntum/calendar-react-thin';
import { calendarConfig } from './AppConfig';
import './App.scss';

const App: FunctionComponent = () => {
    const calendarRef = useRef<BryntumCalendar>(null);
    const calendarInstance = () => calendarRef.current?.instance;

    useEffect(() => {
        // This shows loading data
        // To load data automatically configure crudManager with `autoLoad : true`
        calendarInstance()?.crudManager.load();
    });

    return (
        <Fragment>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumCalendar
                ref = {calendarRef}
                {...calendarConfig}
            />
        </Fragment>
    );
};

export default App;
