// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/react-vite/resourceview/src/App.tsx
import { BryntumCalendar, BryntumDemoHeader } from '@bryntum/calendar-react';
import { calendarConfig } from './AppConfig';

import './App.scss';

function App() {
    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader/>
            <BryntumCalendar {...calendarConfig} />
        </>
    );
}

export default App;

// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/vue-3-vite/timeranges/src/App.vue
<script setup lang="ts">
import { reactive } from 'vue';
import { BryntumDemoHeader, BryntumCalendar } from '@bryntum/calendar-vue-3';
import { calendarConfiguration, timeRangesFeatureConfig, eventTooltipFeatureConfig } from './AppConfig';

const calendarConfig = reactive(calendarConfiguration);

</script>

<template>
    <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
    <bryntum-demo-header />
    <bryntum-calendar
        v-bind = "calendarConfig"
        :eventTooltipFeature = "eventTooltipFeatureConfig"
        :timeRangesFeature = "timeRangesFeatureConfig"
    />
</template>

<style lang="scss">
@import './App.scss';
</style>
