// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/vue-3/javascript/inline-data/src/App.vue
<!-- Application -->
<template>
    <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
    <bryntum-demo-header />
    <bryntum-calendar-project-model
        ref="project"
        :events="events"
        :resources="resources"
    />
    <bryntum-calendar
        ref="calendar"
        v-bind="calendarConfig"
        :project="project"
    />
</template>

<script>
import { ref, reactive } from 'vue';

import {
    BryntumDemoHeader,
    BryntumCalendar,
    BryntumCalendarProjectModel
} from '@bryntum/calendar-vue-3';

import { useCalendarConfig } from '@/AppConfig';
import * as appData from '@/AppData';

export default {
    name : 'App',

    components : {
        BryntumDemoHeader,
        BryntumCalendar,
        BryntumCalendarProjectModel
    },

    setup() {
        const calendar = ref(null);
        const project = ref(null);

        const calendarConfig = reactive(useCalendarConfig());

        const events = ref(appData.events);
        const resources = ref(appData.resources);

        return {
            calendar,
            calendarConfig,
            events,
            resources,
            project
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/react/javascript/inline-data/src/App.js
/**
 * Application
 */
import React, { useRef, useState } from 'react';

import { BryntumCalendar, BryntumDemoHeader, BryntumCalendarProjectModel } from '@bryntum/calendar-react';
import { Toast } from '@bryntum/calendar';

import { calendarConfig } from './AppConfig';
import { projectData } from './AppData';

import './App.scss';

function App() {
    const calendar = useRef();
    const project = useRef();

    const [events] = useState(projectData.events);
    const [resources] = useState(projectData.resources);

    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumCalendarProjectModel
                ref={project}
                events={events}
                resources={resources}
            />
            <BryntumCalendar
                ref={calendar}
                project={project}
                {...calendarConfig}
            />
        </>
    );
}

export default App;


Toast.show({
    color : 'b-orange',
    html  : `
    <p style="color:white;">This demo was created with <strong>Create React App</strong> (CRA).</p>
    <p style="color:white;">Since CRA is deprecated, we recommend you to check out our React Vite demos.</p>
`,
    timeout : 10000
});
