// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/vue-3/javascript/bigdataset/src/App.vue
<!-- Application -->
<template>
    <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
    <bryntum-demo-header />
    <bryntum-calendar
        ref="calendarRef"
        v-bind="calendarConfig"
        :on-active-item-change="onActiveItemChange"
    />
</template>

<script>
// vue imports
import { ref, onMounted } from 'vue';

// app components
import {
    BryntumDemoHeader,
    BryntumCalendar
} from '@bryntum/calendar-vue-3';
import { calendarConfig } from '@/AppConfig';

export default {
    name : 'App',

    components : {
        BryntumDemoHeader,
        BryntumCalendar
    },

    setup() {
        const calendarRef = ref(null);

        function onActiveItemChange({ activeItem }) {
            const calendar = calendarRef.value.instance.value;
            // Only meaningful if we are on the month view
            calendar.widgetMap.autoRowHeight.disabled = activeItem.modeName !== 'month';
        }

        function onAutoRowHeightChanged({ checked }) {
            const calendar = calendarRef.value.instance.value;

            calendar.modes.month.autoRowHeight = checked;
        }

        // Called as the resourceFilterFilter's onChange handler
        function onResourceFilterFilterChange({ value }) {
            const calendar = calendarRef.value.instance.value;
            // A filter with an id replaces any previous filter with that id.
            // Leave any other filters which may be in use in place.
            calendar.widgetMap.resourceFilter.store.filter({
                id       : 'resourceFilterFilter',
                filterBy : r => r.name.toLowerCase().startsWith(value.toLowerCase()) // a function which returns true to include the record
            });
        }

        onMounted(() => {
            const calendar = calendarRef.value.instance.value;

            calendar.widgetMap.autoRowHeight.on({ change : onAutoRowHeightChanged });
            calendar.widgetMap.resourceFilterFilter.on({ change : onResourceFilterFilterChange });
        });

        return {
            calendarConfig,
            onActiveItemChange,
            calendarRef
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// bryntum-calendar-trial/calendar-6.2.1-trial/examples/frameworks/angular/bigdataset/src/app/app.component.ts
import { AfterViewInit, Component, ViewChild, ViewEncapsulation } from '@angular/core';
import { BryntumCalendarComponent } from '@bryntum/calendar-angular';
import { Calendar, Checkbox, FilterField, MonthView, ResourceFilter, Store } from '@bryntum/calendar';
import { calendarProps } from './app.config';

@Component({
    selector      : 'app-root',
    templateUrl   : './app.component.html',
    styleUrls     : ['./app.component.scss'],
    encapsulation : ViewEncapsulation.None
})
export class AppComponent implements AfterViewInit {
    @ViewChild(BryntumCalendarComponent) calendarComponent: BryntumCalendarComponent;

    private calendar: Calendar;
    private resourceFilter: ResourceFilter;
    private resourceFilterFilter: FilterField;
    private autoRowHeight: Checkbox;

    // calendar configuration
    calendarProps = calendarProps;

    onActiveItemChange({ activeItem }: { activeItem: any }): void {
        // Only meaningful if we are on the month view
        this.autoRowHeight.disabled = activeItem.modeName !== 'month';
    }

    onAutoRowHeightChanged({ checked }: { checked: boolean }): void {
        (this.calendar.modes as { month: MonthView }).month.autoRowHeight = checked;
    }

    // Called as the resourceFilterFilter's onChange handler
    onResourceFilterFilterChange({ value }: { value: string }): void {
        // A filter with an id replaces any previous filter with that id.
        // Leave any other filters which may be in use in place.
        (this.resourceFilter.store as Store).filter({
            id       : 'resourceFilterFilter',
            filterBy : r => r.name.toLowerCase().startsWith(value.toLowerCase()) // a function which returns true to include the record
        });
    }

    /**
     * Called after View is initialized
     */
    ngAfterViewInit(): void {
        this.calendar             = this.calendarComponent.instance;
        const { widgetMap }       = this.calendar;
        this.autoRowHeight        = widgetMap['autoRowHeight'] as Checkbox;
        this.resourceFilterFilter = widgetMap['resourceFilterFilter'] as FilterField;
        this.resourceFilter       = widgetMap['resourceFilter'] as ResourceFilter;

        this.autoRowHeight.on({
            change  : this.onAutoRowHeightChanged,
            thisObj : this
        });
        this.resourceFilterFilter.on({
            change  : this.onResourceFilterFilterChange,
            thisObj : this
        });
    }
}

<!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
<bryntum-demo-header></bryntum-demo-header>

<bryntum-calendar
    [date] = "calendarProps.date"
    [weekExpanderFeature] = "calendarProps.weekExpanderFeature"
    [eventEditFeature] = "calendarProps.eventEditFeature"
    [modeDefaults] = "calendarProps.modeDefaults"
    [modes] = "calendarProps.modes"
    [tbar] = "calendarProps.tbar"
    [crudManager] = "calendarProps.crudManager"
    [sidebar] = "calendarProps.sidebar"
    (onActiveItemChange) = "onActiveItemChange($event)"
></bryntum-calendar>
